// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: scs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserModel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DocumentType   string                 `protobuf:"bytes,4,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentNumber string                 `protobuf:"bytes,5,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"`
	CreationDate   string                 `protobuf:"bytes,6,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Blocked        bool                   `protobuf:"varint,7,opt,name=blocked,proto3" json:"blocked,omitempty"`
	AuthId         string                 `protobuf:"bytes,8,opt,name=authId,proto3" json:"authId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_scs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_scs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_scs_proto_rawDescGZIP(), []int{0}
}

func (x *UserModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserModel) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *UserModel) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *UserModel) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *UserModel) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *UserModel) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserModel           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_scs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_scs_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllUsersResponse) GetUsers() []*UserModel {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DocumentType   string                 `protobuf:"bytes,3,opt,name=documentType,proto3" json:"documentType,omitempty"`
	DocumentNumber string                 `protobuf:"bytes,4,opt,name=documentNumber,proto3" json:"documentNumber,omitempty"`
	AuthId         string                 `protobuf:"bytes,5,opt,name=authId,proto3" json:"authId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_scs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_scs_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateUserRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *CreateUserRequest) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *CreateUserRequest) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

type UpdateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DocumentType   string                 `protobuf:"bytes,3,opt,name=documentType,proto3" json:"documentType,omitempty"`
	DocumentNumber string                 `protobuf:"bytes,4,opt,name=documentNumber,proto3" json:"documentNumber,omitempty"`
	Id             string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_scs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_scs_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateUserRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *UpdateUserRequest) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_scs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_scs_proto_rawDescGZIP(), []int{4}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdResponse) Reset() {
	*x = IdResponse{}
	mi := &file_scs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdResponse) ProtoMessage() {}

func (x *IdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdResponse.ProtoReflect.Descriptor instead.
func (*IdResponse) Descriptor() ([]byte, []int) {
	return file_scs_proto_rawDescGZIP(), []int{5}
}

func (x *IdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_scs_proto protoreflect.FileDescriptor

const file_scs_proto_rawDesc = "" +
	"\n" +
	"\tscs.proto\x12\x03uas\x1a\x1bgoogle/protobuf/empty.proto\"\xf6\x01\n" +
	"\tUserModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rdocument_type\x18\x04 \x01(\tR\fdocumentType\x12'\n" +
	"\x0fdocument_number\x18\x05 \x01(\tR\x0edocumentNumber\x12#\n" +
	"\rcreation_date\x18\x06 \x01(\tR\fcreationDate\x12\x18\n" +
	"\ablocked\x18\a \x01(\bR\ablocked\x12\x16\n" +
	"\x06authId\x18\b \x01(\tR\x06authId\";\n" +
	"\x13GetAllUsersResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.uas.UserModelR\x05users\"\xad\x01\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\fdocumentType\x18\x03 \x01(\tR\fdocumentType\x12&\n" +
	"\x0edocumentNumber\x18\x04 \x01(\tR\x0edocumentNumber\x12\x16\n" +
	"\x06authId\x18\x05 \x01(\tR\x06authId\"\xa5\x01\n" +
	"\x11UpdateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\fdocumentType\x18\x03 \x01(\tR\fdocumentType\x12&\n" +
	"\x0edocumentNumber\x18\x04 \x01(\tR\x0edocumentNumber\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"IdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xc5\x02\n" +
	"\vUserService\x125\n" +
	"\n" +
	"CreateUser\x12\x16.uas.CreateUserRequest\x1a\x0f.uas.IdResponse\x12,\n" +
	"\tBlockUser\x12\x0e.uas.IdRequest\x1a\x0f.uas.IdResponse\x12.\n" +
	"\vUnblockUser\x12\x0e.uas.IdRequest\x1a\x0f.uas.IdResponse\x125\n" +
	"\n" +
	"UpdateUser\x12\x16.uas.UpdateUserRequest\x1a\x0f.uas.IdResponse\x12)\n" +
	"\aGetById\x12\x0e.uas.IdRequest\x1a\x0e.uas.UserModel\x12?\n" +
	"\vGetAllUsers\x12\x16.google.protobuf.Empty\x1a\x18.uas.GetAllUsersResponseB'Z%github.com/igntnk/stocky-scs/proto/pbb\x06proto3"

var (
	file_scs_proto_rawDescOnce sync.Once
	file_scs_proto_rawDescData []byte
)

func file_scs_proto_rawDescGZIP() []byte {
	file_scs_proto_rawDescOnce.Do(func() {
		file_scs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scs_proto_rawDesc), len(file_scs_proto_rawDesc)))
	})
	return file_scs_proto_rawDescData
}

var file_scs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scs_proto_goTypes = []any{
	(*UserModel)(nil),           // 0: uas.UserModel
	(*GetAllUsersResponse)(nil), // 1: uas.GetAllUsersResponse
	(*CreateUserRequest)(nil),   // 2: uas.CreateUserRequest
	(*UpdateUserRequest)(nil),   // 3: uas.UpdateUserRequest
	(*IdRequest)(nil),           // 4: uas.IdRequest
	(*IdResponse)(nil),          // 5: uas.IdResponse
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_scs_proto_depIdxs = []int32{
	0, // 0: uas.GetAllUsersResponse.users:type_name -> uas.UserModel
	2, // 1: uas.UserService.CreateUser:input_type -> uas.CreateUserRequest
	4, // 2: uas.UserService.BlockUser:input_type -> uas.IdRequest
	4, // 3: uas.UserService.UnblockUser:input_type -> uas.IdRequest
	3, // 4: uas.UserService.UpdateUser:input_type -> uas.UpdateUserRequest
	4, // 5: uas.UserService.GetById:input_type -> uas.IdRequest
	6, // 6: uas.UserService.GetAllUsers:input_type -> google.protobuf.Empty
	5, // 7: uas.UserService.CreateUser:output_type -> uas.IdResponse
	5, // 8: uas.UserService.BlockUser:output_type -> uas.IdResponse
	5, // 9: uas.UserService.UnblockUser:output_type -> uas.IdResponse
	5, // 10: uas.UserService.UpdateUser:output_type -> uas.IdResponse
	0, // 11: uas.UserService.GetById:output_type -> uas.UserModel
	1, // 12: uas.UserService.GetAllUsers:output_type -> uas.GetAllUsersResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scs_proto_init() }
func file_scs_proto_init() {
	if File_scs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scs_proto_rawDesc), len(file_scs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scs_proto_goTypes,
		DependencyIndexes: file_scs_proto_depIdxs,
		MessageInfos:      file_scs_proto_msgTypes,
	}.Build()
	File_scs_proto = out.File
	file_scs_proto_goTypes = nil
	file_scs_proto_depIdxs = nil
}
